apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-helm-chart.fullname" . }}-manager-role
  labels:
  {{- include "operator-helm-chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - flyte.backend
  resources:
  - flyteregistrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flyte.backend
  resources:
  - flyteregistrations/finalizers
  verbs:
  - update
- apiGroups:
  - flyte.backend
  resources:
  - flyteregistrations/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator-helm-chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project
    app.kubernetes.io/part-of: project
  {{- include "operator-helm-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "operator-helm-chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "operator-helm-chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'