apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator-helm-chart.fullname" . }}-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: project
    app.kubernetes.io/part-of: project
    control-plane: controller-manager
  {{- include "operator-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "operator-helm-chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}