apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "operator-helm-chart.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project
    app.kubernetes.io/part-of: project
  {{- include "operator-helm-chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}