# permissions for end users to view flyteregistrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: flyteregistration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project
    app.kubernetes.io/part-of: project
    app.kubernetes.io/managed-by: kustomize
  name: flyteregistration-viewer-role
rules:
  - apiGroups:
      - flyte.backend
    resources:
      - flyteregistrations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - flyte.backend
    resources:
      - flyteregistrations/status
    verbs:
      - get
