controllerManager:
  manager:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      awsRegion: eu-west-2
      logLevel: info
      downloaderStrategy: oci
      ociRegistry: ""
      ociAuthStrategy: ecr
      ociUsername: ""
      ociPassword: ""
      jFrogArtifactoryUrl: ""
      jFrogUser: ""
      jFrogPassword: ""
      flyteAdminEndpoint: ""
    image:
      repository: adarga/flyte-workflow-registration-operator
      tag: 1.0.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
