name: Push Artifacts

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push-docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag without 'v'
        id: extract_tag
        run: echo "TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            adarga/flyte-workflow-registration-operator:${{ env.TAG }}
            adarga/flyte-workflow-registration-operator:latest

  push-helm-chart:
    name: Push Helm chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package Helm chart
        run: helm package helm

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Helm chart to Docker Hub
        run: |
          CHART_VERSION=$(cat helm/Chart.yaml | grep '^version:' | awk '{print $2}')
          helm push flyte-workflow-registration-operator-chart-${CHART_VERSION}.tgz oci://registry-1.docker.io/adarga