name: Semantic Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45
        with:
          github-token: ${{ secrets.ADARGA_GITHUB_PAT }}